// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSKT70pXHHNF3CzWrg0TA4YO8d49meVE',
    appId: '1:85396120151:web:219c41b1fff41e02337912',
    messagingSenderId: '85396120151',
    projectId: 'quizproflutter',
    authDomain: 'quizproflutter.firebaseapp.com',
    storageBucket: 'quizproflutter.firebasestorage.app',
    measurementId: 'G-H96GB3ZG0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR0oOYE7JNVjTLATuBe9s_LeWZyj5K8lk',
    appId: '1:85396120151:android:591d6cc1517c2c26337912',
    messagingSenderId: '85396120151',
    projectId: 'quizproflutter',
    storageBucket: 'quizproflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZuayapR1x4YbZhrW7NsOpHKM5xtnIWb8',
    appId: '1:85396120151:ios:329498781cdaa92f337912',
    messagingSenderId: '85396120151',
    projectId: 'quizproflutter',
    storageBucket: 'quizproflutter.firebasestorage.app',
    iosBundleId: 'com.example.quizproflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZuayapR1x4YbZhrW7NsOpHKM5xtnIWb8',
    appId: '1:85396120151:ios:329498781cdaa92f337912',
    messagingSenderId: '85396120151',
    projectId: 'quizproflutter',
    storageBucket: 'quizproflutter.firebasestorage.app',
    iosBundleId: 'com.example.quizproflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSKT70pXHHNF3CzWrg0TA4YO8d49meVE',
    appId: '1:85396120151:web:ed862c76d851d2a8337912',
    messagingSenderId: '85396120151',
    projectId: 'quizproflutter',
    authDomain: 'quizproflutter.firebaseapp.com',
    storageBucket: 'quizproflutter.firebasestorage.app',
    measurementId: 'G-SLD526J8BP',
  );
}
