// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldxDPrY4-_stJ3iHvHPhc7GxhnxqVfjQ',
    appId: '1:122021072464:web:d8c278cc650a4e3f964b55',
    messagingSenderId: '122021072464',
    projectId: 'awesomeproject-bfb59',
    authDomain: 'awesomeproject-bfb59.firebaseapp.com',
    storageBucket: 'awesomeproject-bfb59.firebasestorage.app',
    measurementId: 'G-ZZBH9WJ3HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgAYnj9Jr7c8i4mYt18zacVfneuyb6Do',
    appId: '1:122021072464:android:54d0521618b4ae01964b55',
    messagingSenderId: '122021072464',
    projectId: 'awesomeproject-bfb59',
    storageBucket: 'awesomeproject-bfb59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLym3QrYoSLk4JJoRVQuyXmX0HMzUDfo',
    appId: '1:122021072464:ios:ff515b3bd9b92456964b55',
    messagingSenderId: '122021072464',
    projectId: 'awesomeproject-bfb59',
    storageBucket: 'awesomeproject-bfb59.firebasestorage.app',
    iosBundleId: 'com.example.quizproflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLym3QrYoSLk4JJoRVQuyXmX0HMzUDfo',
    appId: '1:122021072464:ios:ff515b3bd9b92456964b55',
    messagingSenderId: '122021072464',
    projectId: 'awesomeproject-bfb59',
    storageBucket: 'awesomeproject-bfb59.firebasestorage.app',
    iosBundleId: 'com.example.quizproflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCybNjC9H0AU1mEaOFQtH2ZYay0JSZIBo8',
    appId: '1:122021072464:web:3ff17ade0d1faa83964b55',
    messagingSenderId: '122021072464',
    projectId: 'awesomeproject-bfb59',
    authDomain: 'awesomeproject-bfb59.firebaseapp.com',
    storageBucket: 'awesomeproject-bfb59.firebasestorage.app',
    measurementId: 'G-VEDM9MVQFQ',
  );
}
